// *********** NODEMON ************

        // AUTO RESTARTS THE SERVER AFTER CHANGES ARE MADE, SO YOU DON'T HAVE TO DO IT MANUALLY.
            // npm install -g // THE -g FLAG STATES THAT WE ARE INSTALLING THIS PACKAGE FOR GLOBAL USE ON OUR MACHINE;
            // MEANING WE CAN USE IT NOT ONLY FOR THIS PROJECT, BUT ALSO FOR FUTURE PROJECTS ON OUR COMPUTER.

        // ******** node_modules DIR IS AUTO CREATED WHENEVER A LOCAL PACKEAGE IS INSTALLED    


  //********** DEPENDENCIES ***********/
  
        // node_moduels DIR IS TIPICALLY NOT PUSHED UP TO GITHUB.
        // package.json WILL LIST ALL REQUIRED DEPENDENCIES FOR PROJECT.
            // RUNNIG npm install WILL INSTALL AL LISTED MODULES/DEPENDENCIES. (DON'T HAVE TO DO EACH ONE INDIVIDUALLY.);