
 //******** CREATING A SERVER ********

    const http = require("http"); //NEED TO IMPORT THE "http" NODE CORE MODULE.

    // vvv FOR ILLUSTRATION ONLY. SERVER INSTANCE CAN BE STORED IN A VARIABLE FOR USE SOMEWHERE ELSE.
    // const testServer = http.createServer();

    // TAKES IN ONE ARG THAT IS A CALLBACK FUNCTION.
    // CALLBACK FUNCTION WILL RUN EVERTIME A REQUEST COMES INTO OUR SERVER.
    // CALLBACK FUNCTION GIVES US ACCESS TO TWO OBJS (req, res).
    // req OBJ = CONTAINS INFO SUCH AS URL, REQ TYPE (GET, POST, DELETE), AND OTEHR INFO.
    // res OBJ = THIS OBJ IS USED TO SEND A RESPONSE TO THE USER.
    
        const testServer = http.createServer((req, res) => {
                console.log("request made");
            });
    // ^^^ AT THIS POINT testServer IS NOT ACTUALLY DOING ANYTHING, IT'S NOT ACTIVELY LISTENING FOR ANY REQUESTS BEING SENT TO IT.

    // vvv TO ACTIVATE AND USE THIS SERVER WE HAVE TO INVOKE THE listen() METHOD.
    // listen() METHOD ACCEPTS A PORT NUMBER AS AN ARG, AND A SECOND ARG THAT IS THE HOST NAME. DEFAULT 2ND ARG IS "localhost". THE THIRD ARG IS A FUNCTION THAT IS CALLED THE SERVER STARTS LISTENING.

        testServer.listen(3000, "localhost", () => {
            console.log("listening for requests on port 3000");
        });


 //******** LOCAHOST AND PORT NUMBERS ***********
 
        // LOCALHOST IS LIKE A DOMAIN NAME ON THE WEB.
            // THIS "localhost" DOMAIN TAKE TO A VERY SPECIFIC IP ADDRESS CALLED A LOOPBACK IP ADDRESS.
            // THIS "localhost" IP IS 127.0.0.1 AND ROUTES US BCAK DIRECTLY TO YOUR COMPUTER.
            // THIS MEANS WHEN WE CONNECT TO A localhost IN OUR BROWSER THE BROWSER IS CONNECTING BACK TO OUR OWN COMPUTER, WHICH IS THEN ACTING AS A HOST FOR OUR WEBSITE.
            // THE HOST NAME localhost MEANS LISTEN FOR REQUESTS COMING TO OUR OWN COMPUTER.

        // PORT NUMBERS:
            // ARE LIKE DOORS INTO A COMPUTER IN WHICH INTERNET COMMS CAN BE MADE TO DIFFERENT PROGRAMS.
            // PORT NUMS REPRESENT A SPECIFIC CHANNEL/GATEWAY WHERE A CERTAIN PIECE OF SOFTWARE SHOULD COMMUNICATE THROUGH.
            // SOFTWARE SUCH AS EMAIL CLIENTS, SKYPE, ETC

        
            // OUR SERVER ALSO NEED ITS OWN PORT NUMBER (MOST OF THE TIME FOR DEV PRUPOSES ITS 3000). 
            // CAN BE ANY PORT NUM AS LONG AS ITS NOT BEING USED BY ANOTHER PROGRAM.
                // localhost:3000
                // control + c TO STOP THE SERVER.


