//********* MIDDLEWARE NOTES ***********

    // MIDDLEWARE IS CODE WHICH RUNS (ON THE SERVER) BETWEEN GETTING A REQUEST AND SENDING A RESPONSE.

    // REQUEST ---> [SERVER ----> CODE/FUNCTION (MIDDLEWARE) ----> SERVER] ----> RESPONSE

    // .use() METHOD IS GENERALLY USED TO RUN MIDDLEWARE (WE USED IT TO HANDLE OUR 404 CASES)

    // CAN HAVE MULTIPLE MIDDLEWARE FUNCTIONS RUN IN BETWEEN A REQUEST AND RESPONSE.

    //ANOTHER EXAMPLE OF MW FUNCTOINS ARE THE FUNCTIONS THAT RUN IN OUR .get() METHODS EX: app.get("/about", (req, res) => { };

    // THE ORDER OF MIDDLEWARE IS IMPORTANT. USED IT IN app.js TO SET THE OUR 404 AS THE LAST OPTION IN OUR ROUTER.